[package]
name = "mhw_toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21", optional = true }
mlua = { version = "0.9.4", features = ["lua54", "vendored"], optional = true }
once_cell = "1.19.0"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
winapi = { version = "0.3.9", features = ["winuser", "stringapiset", "winnls"] }
tokio = { version = "1.36.0", features = ["full"], optional = true }

[features]
default = []
lua_engine = ["mlua"]
logger = ["log"]
async-tokio = ["tokio"]